settings:
  title: 'Status Page'
  url: 'https://status.yuyangwang.org/' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: www-yuyangwang-org # unique identifier
    name: www.yuyangwang.org (Yuyang Wang's Site.)
    url: 'https://www.yuyangwang.org/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: yuyangwang-org # unique identifier
    name: yuyangwang.org (Yuyang Wang's Site Alias.)
    url: 'https://yuyangwang.org/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: echo-cool # unique identifier
    name: echo.cool (Yuyang Wang's Blog.)
    url: 'https://echo.cool/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: overleaf-echo-cool # unique identifier
    name: overleaf.echo.cool (ShareLaTeX Instance Hosted at echo.cool)
    url: 'https://overleaf.echo.cool/login' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: git-echo-cool
    name: git.echo.cool (Gitea Instance Hosted at echo.cool)
    url: 'https://git.echo.cool/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: jenkins-echo-cool
    name: jenkins.echo.cool (Jenkins Instance Hosted at echo.cool)
    url: 'https://jenkins.echo.cool/login'
    method: GET
    expectStatus: 200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: pm3-echo-cool
    name: pm3.echo.cool (Proxmark3 Blog)
    url: 'https://pm3.echo.cool/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: bdic-api-bj
    name: bjbdicapi.echo.cool (WeChat Mini-program We-BDIC API Django [Beijing])
    url: 'https://bjbdicapi.echo.cool/'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

  - id: bdic-api-remote
    name: aliyunapi.echo.cool (WeChat Mini-program We-BDIC API Cloud Function [France])
    url: 'http://aliyunapi.echo.cool/'
    method: POST
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

  - id: ucd-sisweb
    name: sisweb.ucd.ie (We-BDIC - UCD Student Information System)
    url: 'https://hub.ucd.ie'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true


