settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: www-yuyangwang-org # unique identifier
    name: www.yuyangwang.org
    description: 'Yuyang Wang"s Site.' # default=empty
    url: 'https://www.yuyangwang.org/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: yuyangwang-org # unique identifier
    name: yuyangwang.org
    description: 'Yuyang Wang"s Site.' # default=empty
    url: 'https://yuyangwang.org/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: overleaf-echo-cool # unique identifier
    name: overleaf.echo.cool
    description: 'Overleaf Hosted on echo.cool' # default=empty
    url: 'https://overleaf.echo.cool/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: git-echo-cool
    name: git.echo.cool
    description: 'My Gitea Instance on echo.cool'
    url: 'https://git.echo.cool/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: jenkins-echo-cool
    name: jenkins.echo.cool
    description: 'My Jenkins Instance on echo.cool'
    url: 'https://jenkins.echo.cool/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: bdic-api-bj
    name: bjbdicapi.echo.cool
    description: "BDIC API on echo.cool Beijing"
    url: 'https://bjbdicapi.echo.cool/'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

  - id: bdic-api-remote
    name: bjbdicapi.echo.cool
    description: "BDIC API on Aliyun POST"
    url: 'http://aliyunapi.echo.cool/'
    method: POST
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

  - id: ucd-sisweb
    name: sisweb.ucd.ie
    description: "UCD Student Information System"
    url: 'https://sisweb.ucd.ie/'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true
